Changes get() return type to support proxy iterators (like std::vector<bool>)
A new test for std::vector<bool> was added. This new test would emit the following errors in GCC 5.2 before this fix:

    product_iterator_impl.hpp:62:31: error: returning reference to temporary [-Werror=return-local-addr]
       return *std::get<I>(current_);
                                   ^
    product_iterator_impl.hpp: In instantiation of ‘const typename std::tuple_element<I, std::tuple<const typename std::remove_reference<typename Containers::value_type>::type& ...> >::type& product_iterator<Containers>::get() const [with long unsigned int I = 1ul; Containers = {std::vector<bool, std::allocator<bool> >, std::vector<bool, std::allocator<bool> >}; typename std::tuple_element<I, std::tuple<const typename std::remove_reference<typename Containers::value_type>::type& ...> >::type = const bool&]’